# Generated by Django 5.0 on 2023-12-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('telegram_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('language', models.IntegerField()),
            ],
        ),
    ]
