# Generated by Django 5.0 on 2023-12-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0005_categoryimage'),
        ('for_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_admin.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_user.botusers')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('orders', models.ManyToManyField(to='for_user.basket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='for_user.botusers')),
            ],
        ),
    ]
