# Generated by Django 5.0 on 2023-12-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0003_alter_botusers_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
