# Generated by Django 5.0 on 2024-01-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0005_basket_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
