# Generated by Django 5.0 on 2024-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_user', '0006_order_delivered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='latitude',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='longitude',
            field=models.CharField(max_length=100),
        ),
    ]
