# Generated by Django 5.0 on 2023-12-12 10:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('for_admin', '0007_alter_categories_image_alter_categoryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[640, 640], upload_to='category_images'),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[640, 640], upload_to='category_main'),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[640, 640], upload_to='product_images'),
        ),
    ]
